module Api
  class DocsController < ApplicationController
    # Allow unauthenticated access to API documentation
    skip_before_action :verify_authenticity_token
    before_action :skip_browser_check

    # GET /api/rest
    # Renders the interactive REST API reference powered by Redoc
    def rest
      render layout: false
    end

    # GET /api/graphql
    # Serves the GraphQL API reference generated by SpectaQL
    def graphql
      send_file Rails.root.join("public/graphql-docs/index.html"),
                type: "text/html",
                disposition: "inline"
    end

    private

    def skip_browser_check
      # Override allow_browser check for documentation pages
    end
  end
end

