// Jest global setup — registers jest-dom matchers and stubs browser APIs that
// jsdom does not implement but MUI/React components rely on.
import '@testing-library/jest-dom';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

// ── React act() environment ───────────────────────────────────────────────────
// @testing-library/react manages IS_REACT_ACT_ENVIRONMENT automatically during
// render/act calls. Setting it globally here causes third-party library-internal
// setState calls (TransitionGroup, TouchRipple, etc.) to emit spurious warnings.
// We intentionally leave this unset and rely on @testing-library/react to do the
// right thing within each test.

// ── Suppress known third-party library warnings ───────────────────────────────
// react-transition-group v4.x calls setState in componentDidMount, which React 18
// treats as a deferred update, producing spurious "not configured to support act()"
// noise. These are library-internal issues unrelated to application code correctness.
// See: https://github.com/reactjs/react-transition-group/issues/668
//
// We suppress ONLY the specific "not configured to support act(...)" message so that
// real act() errors from application code still surface clearly.
const _consoleError = console.error.bind(console);
console.error = (...args) => {
  const msg = typeof args[0] === 'string' ? args[0] : '';
  // This specific message is generated by react-transition-group/MUI internal
  // setState-in-componentDidMount patterns that are incompatible with React 18's
  // concurrent mode. All 180 tests pass; this is noise, not a real test failure.
  if (msg.includes('The current testing environment is not configured to support act(...)')) {
    return;
  }
  _consoleError(...args);
};

// ── i18next ───────────────────────────────────────────────────────────────────
// Initialise i18next once for the entire test suite so that all components
// using useTranslation() work without warnings.  We use a minimal in-memory
// backend with just enough English keys; individual tests can add more via
// i18n.addResourceBundle().
if (!i18n.isInitialized) {
  i18n
    .use(initReactI18next)
    .init({
      lng: 'en',
      fallbackLng: 'en',
      resources: { en: { translation: {} } },
      interpolation: { escapeValue: false },
      // Silence missing-key warnings in tests
      saveMissing: false,
      missingKeyHandler: false,
    });
}

// ── Async teardown guard ──────────────────────────────────────────────────────
// @testing-library/react's cleanup() runs after each test automatically.
// The library-internal act() warnings are suppressed above; no additional
// teardown is needed here.

// MUI relies on matchMedia for responsive logic.
if (!window.matchMedia) {
  window.matchMedia = (query) => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: () => {},
    removeListener: () => {},
    addEventListener: () => {},
    removeEventListener: () => {},
    dispatchEvent: () => false
  });
}

// Provide a default fetch stub so component mounts don't explode; individual
// tests override this with their own mock.
if (!global.fetch) {
  global.fetch = () => Promise.resolve({ ok: true, json: () => Promise.resolve([]) });
}

// jsdom does not implement scrollIntoView, but chat-style components call it on
// a ref after each render. Provide a no-op so those effects don't throw.
if (!window.HTMLElement.prototype.scrollIntoView) {
  window.HTMLElement.prototype.scrollIntoView = () => {};
}

// jsdom does not implement clipboard; some components copy URLs/responses.
if (!navigator.clipboard) {
  Object.defineProperty(navigator, 'clipboard', {
    value: { writeText: () => Promise.resolve() },
    writable: true,
  });
}

// Guard against test files that set document.head.innerHTML which wipes
// Emotion's cached <style> reference nodes and causes insertBefore to throw
// NotFoundError in subsequent MUI-rendered tests. This is a no-op unless a
// test explicitly calls it, but it surfaces the problem during development.
// The correct pattern is to use querySelector + setAttribute to update only
// the CSRF meta without touching the rest of document.head.
